/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AMI_JNI */

#ifndef _Included_AMI_JNI
#define _Included_AMI_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AMI_JNI
 * Method:    get_maker
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1maker
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_model
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1model
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_serial_num
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1serial_1num
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1reboot
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_factory_reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1factory_1reboot
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    available_pwr_source
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_available_1pwr_1source
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_voltage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1voltage
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_current
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1current
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_free_memory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1free_1memory
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cur_time
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cur_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_cur_time
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_set_1cur_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_time_zone
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1time_1zone
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_time_zone
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_set_1time_1zone
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_dev_type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1dev_1type
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_hw_ver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1hw_1ver
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_total_memory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1total_1memory
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rsrp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1rsrp
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rsrq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1rsrq
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_ip_address
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1ip_1address
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cell_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1cell_1id
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_mnc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1mnc
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_mcc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1mcc
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_snr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1snr
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_fw_ver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1fw_1ver
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_tx_data_count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1tx_1data_1count
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rx_data_count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1rx_1data_1count
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_trx_data_clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_set_1trx_1data_1clear
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_data_collect_start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_exe_1data_1collect_1start
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_data_collect_stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_exe_1data_1collect_1stop
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_data_collect_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1data_1collect_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_data_collect_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_set_1data_1collect_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_ami_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1ami_1name
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_ami_type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1ami_1type
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_ami_date
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1ami_1date
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cpu_maker
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cpu_1maker
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cpu_model
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cpu_1model
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cpu_rate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cpu_1rate
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_ram_rate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1ram_1rate
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_mear_pwr_vlt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1mear_1pwr_1vlt
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_mear_cons_cur
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1mear_1cons_1cur
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_factory_reboot_amicc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1factory_1reboot_1amicc
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_last_reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1last_1reboot
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_pwr_off_time
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1pwr_1off_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_pwr_on_time
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1pwr_1on_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_wdt_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_exe_1wdt_1test
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_self_reset_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1self_1reset_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_self_reset_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_set_1self_1reset_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_self_reset_time
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1self_1reset_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_self_reset_time
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_set_1self_1reset_1time
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rs485dlb_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1rs485dlb_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_rs485dlb_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_set_1rs485dlb_1period
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_rs485dlb_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1rs485dlb_1start
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_rs485dlb_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1rs485dlb_1stop
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    set_rs485dlb_test_input_data
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_set_1rs485dlb_1test_1input_1data
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rs485dlb_test_input_data
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1rs485dlb_1test_1input_1data
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_rs485dlb_test_output_data
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1rs485dlb_1test_1output_1data
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_led_test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1led_1test
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_wan_code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1wan_1code
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_communication_code
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1communication_1code
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_telecom_company
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1telecom_1company
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_phone_number
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1phone_1number
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_tx_power
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AMI_JNI_get_1tx_1power
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_os_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1os_1name
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_os_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1os_1version
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cypher_module_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cypher_1module_1version
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_cypher_sw_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1cypher_1sw_1version
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_cypher_test_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1cypher_1test_1start
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_cypher_test_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1cypher_1test_1stop
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_integrity_test_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1integrity_1test_1start
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_integrity_test_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1integrity_1test_1stop
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    exe_module_open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AMI_JNI_exe_1module_1open
  (JNIEnv *, jobject);

/*
 * Class:     AMI_JNI
 * Method:    get_date_time
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AMI_JNI_get_1date_1time
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
